version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 github_finder.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-prod-key-replace-in-env
      - ALLOWED_HOSTS=*

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
