# Generated by Django 5.2.17 on 2026-08-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('repo_name', models.CharField(max_length=200)),
                ('data_json', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repository Cache',
                'verbose_name_plural': 'Repository Caches',
                'unique_together': {('username', 'repo_name')},
            },
        ),
    ]
